version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host # Or use specific port mappings if not using host mode
    volumes:
      - ./adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/conf:/opt/adguardhome/conf
    # If not using network_mode: host, you would define ports like this:
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp" # DHCP server
    #   - "68:68/udp" # DHCP server
    #   - "80:80/tcp" # Web interface (if not using 3000)
    #   - "443:443/tcp" # HTTPS web interface
    #   - "3000:3000/tcp" # Web interface default
    #   - "853:853/tcp" # DNS over TLS
    #   - "784:784/udp" # DNS over QUIC
    #   - "853:853/udp" # DNS over QUIC
    #   - "5443:5443/tcp" # DNSCrypt
    #   - "5443:5443/udp" # DNSCrypt
